### ISSUE TITLE
Transfer Slenium tests from Python to JavaScript and switch completely to Playwright

### ISSUE THREAD

**Issue by OmarAleryani10** [remsfal/remsfal.github.io#1]

**Comment by astanik** [comment]
https://github.com/remsfal/remsfal.github.io/pull/2

**Comment by astanik** [comment]
@OmarAleryani10 Unfortunately, the workflow file seems to be not valid.

see: https://github.com/remsfal/remsfal.github.io/actions/runs/7277483401

**Comment by astanik** [comment]
Tests should be implemented in /tests/....

An example can be found in tests-examples/demo-todo-app.spec.js
